export const db = {
  triangle: {
    title: "Triangle",
    desc: "Runs the triangle WebAssembly build generated by the rhio examples pipeline.",
    tags: ["WASM"],
    assetBase: "examples/bin",
    loader: "triangle.js",
    wasm: "triangle.wasm",
    source: "examples/src/triangle.cpp",
    sourceName: "triangle.cpp"
  }
};
